env:
  commonjs: true
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'airbnb-typescript/base'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  project: ["tsconfig.json"]
plugins:
  - '@typescript-eslint'
rules: {
  "no-console": 0,
  "no-var-requires": 0
}
